# Pull md-files from repo`s Wiki and commit it to repository root.

name: wiki-to-repo

on:
    workflow_dispatch:

jobs:
  from-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        ref: ${{ github.head_ref }}
    - name: Clone wiki repo
      run: git clone https://github.com/devalv/notes.wiki.git && ls -lah
    - name: Copy md files from Wiki
      run: cp -f notes.wiki/*.md .
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic changes from Wiki
        branch: master
        file_pattern: ./*.md
